### ISSUE TITLE
Package Internalizer - Add --no-progress to not show download counters

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#104]
### What You Are Seeing?
`choco download adobereader --no-progress`  still shows download counters

### What is Expected?
Download counter output should be surpressed

## References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/300)

**Comment by Chirishman** [comment]
I am also seeing this in my Jenkins logs

**Comment by ferventcoder** [comment]
This is completed and will be released with Chocolatey Licensed Extension vNext (likely v2.0.4).

**Comment by ferventcoder** [comment]
Chocolatey Licensed Extension v 2.1.0
