### ISSUE TITLE
Package Internalizer - download should include an option for virus checking

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#108]
If VirusChecking is enabled in chocolatey, internalizer should run those same checks

### References
[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/183)

**Comment by AdmiringWorm** [comment]
@steviecoaster as the internalizer isn't available in the pro edition, marking it with the pro label probably isn't correct?

**Comment by ferventcoder** [comment]
This is completed and will be released with Chocolatey Licensed Extension v2.1.0.
