### ISSUE TITLE
Central Management - Error on installation 'HTTP Error 500.21 - Internal Server Error Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list'

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#114]
After installation of chocolatey-management-web, upon going to the site you see an error:

* Locally - `HTTP Error 500.21 - Internal Server Error Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list`
* Remotely - `500 - Internal server error`

If you run a `choco list -lo` and you find dotnetcore-windowshosting to be at v3+, you are going to hit this error.

## Workaround

Please uninstall the following packages:

* `choco uninstall aspnetcore-runtimepackagestore`
* `choco uninstall dotnetcore-windowshosting`

Install version 2.2.7 of both packages

* `choco install aspnetcore-runtimepackagestore --version="'2.2.7'"`
* `choco install dotnetcore-windowshosting --version="'2.2.7'"`
* Perform an IIS Reset before you try to hit the web ui again.

## Referenced Issues
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/135)
* [ZenDesk](https://chocolatey.zendesk.com/hc/requests/4863)

**Comment by ferventcoder** [comment]
On the chocolatey-management-web package, there are dependencies on the following packages:

* aspnetcore-runtimepackagestore
* dotnetcore-windowshosting

These packages have recently moved to package version 3.0.0, which is incompatible with the web package. 

These have been pinned to less than 3.0, but won't be released until v0.1.1.

**Comment by gep13** [comment]
This is completed to be released with CCM v0.1.1
