### ISSUE TITLE
Central Management - Dark Theme for Website

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#115]
This should be configurable on a per-user basis.

## Referenced Issues
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/137)
* [ZenDesk](https://chocolatey.zendesk.com/hc/requests/5145)

**Comment by ryanrichter94** [comment]
This has been released as part of the CCM 0.10.0 release
