### ISSUE TITLE
PackageBuilder/PackageUploader - Authenticode sign assemblies

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#116]
Currently, the PackageBuilder.exe and PackageUploader.exe are not signed with the Chocolatey Authenticode Certificate.  This means that they can't be used in any environment using AppLocker.  These assemblies should be signed in the same way that other Chocolatey assemblies are.

## Referenced Issues
* [Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/310)
* [ZenDesk](https://chocolatey.zendesk.com/agent/tickets/5227)

**Comment by verzada** [comment]
Watching.

**Comment by ferventcoder** [comment]
This has been completed for Chocolatey Licensed Extension v2.0.3. The labels will be updated to `4 - Released` once we release the extension.
