### ISSUE TITLE
Chocolatey-Agent keeping a handle on the root named pipe. 

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/chocolatey-licensed-issues#12]
### What You Are Seeing?
Chocolaty background agent interfering with other applications using WCF pipes, by having a handle on the root named pipe. net.pipe://+/ 

This is causing issues with a ReSharper Product that also uses WCF pipes. 

### What is Expected?
both to work in peace and harmony. 

### How Did You Get This To Happen? (Steps to Reproduce)

```
[11:37:45][+0] C:\Windows
 ? handle.exe net.pipe

Handle v3.46
Copyright (C) 1997-2011 Mark Russinovich
Sysinternals - www.sysinternals.com

chocolatey-agent.exe pid: 3252   type: Section        468: \BaseNamedObjects\net.pipe:EbmV0LnBpcGU6Ly8rLw==
[11:37:51][+1] C:\Windows
 ? [System.Text.Encoding]::utf8.GetString([convert]::FromBase64String("bmVOLnBpcGU6Ly8rLw=="))
neN.pipe://+/
[11:37:56][+0] C:\Windows

# Please excuse the poor decoding, i only had Powershell
```

**Comment by ferventcoder** [comment]
This looks to be of particular high priority, so we'll likely issue a fix in quick succession once we get to the bottom of the issue. Thanks for bringing this to our attention.

**Comment by ferventcoder** [comment]
* https://bitbucket.org/chocolatey/chocolicensed/issues/141/ for licensed extension issue.

**Comment by ferventcoder** [comment]
We've released new versions of the agent and the licensed extension to fix this issue.

* https://groups.google.com/forum/#!topic/chocolatey-announce/sU0C5taa1h0
* https://groups.google.com/forum/#!topic/chocolatey-announce/l4EAIwyB4hc
