### ISSUE TITLE
CentralManagement - Friendly names are not saved

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#125]
### What You Are Seeing?
When attempting to set a friendly name, the save button doesn't save the changes, and the modal doesn't close.

### What is Expected?
The friendly name is saved

CCM v0.1.1

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/265)

**Comment by sbrown-tecracer** [comment]
Hello,

Not sure what time scales are reflected for Business License issues but is there any sort of feedback / information coming back from Chocolatey Support here? 

The CCM was the main factor for purchasing licenses but all it can actually do at the moment is report on installed software...whereby the documentation describes a great deal more.

Any News?

Regards,
Sean Brown
(tecRacer)

**Comment by gep13** [comment]
>@sbrown-tecracer said...
whereby the documentation describes a great deal more

Can you confirm what documentation you are referring to here?

**Comment by ferventcoder** [comment]
This is fixed for the next release of Chocolatey Central Management - likely v0.2.0.
