### ISSUE TITLE
CentralManagement - Feature Request: HasOutdatedPackages Column

### ISSUE THREAD

**Issue by Chirishman** [chocolatey/chocolatey-licensed-issues#126]
It would be very helpful to be able to view and report on the presence or absence of outdated packages on a computer overview level, rather than having to go to each specific package and find the listed computers.

Most especially since remediation is more likely to be “cup all” rather than “cup packagexyz” this would make it much easier to create a target-list for patching.

**Comment by mkevenaar** [comment]
@Chirishman is this a duplicate of #119 ?

**Comment by Chirishman** [comment]
@mkevenaar Yep, looks like! Sorry for the duplicate, I emailed support and they asked me to open an issue here.
