### ISSUE TITLE
Central Management - Recaptcha Broken on Registration Page

### ISSUE THREAD

**Issue by Chirishman** [chocolatey/chocolatey-licensed-issues#128]
### What You Are Seeing?

On the user registration page I get an error message of "Site code invalid for domain" with no place in the webui or any config file that I have located to set a site code.

## References
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/394)

**Comment by ferventcoder** [comment]
@Chirishman have you filed a support ticket on this one? We need to capture some specifics and I think this could potentially be something that could go out with a v0.1.2 hotfix so I'd like to capture those asap.

**Comment by ferventcoder** [comment]
@designxsteph @steviecoaster for visibility.

**Comment by ferventcoder** [comment]
@Chirishman checking back in, not sure if there was a ticket filed on this or not.

**Comment by ferventcoder** [comment]
This is fixed and will be released in Central Management v0.2.0
