### ISSUE TITLE
Central Management - Please Update Documentation to Include LDAP feature

### ISSUE THREAD

**Issue by Chirishman** [chocolatey/chocolatey-licensed-issues#129]
Crosspost from the main website repo: https://github.com/chocolatey/chocolatey.org/issues/846

Please enhance the [Central Management documentation](https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Documentation/Files/FeaturesChocolateyCentralManagement.md) to include an explanation of the LDAP support [mentioned in the release notes](https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Documentation/Files/ReleaseNotesCentralManagement.md)

**Comment by ryanrichter94** [comment]
@Chirishman Are you referring to the LDAP setup documentation here: https://docs.chocolatey.org/en-us/central-management/setup/website#step-4.3-ldap-configuration

**Comment by vexx32** [comment]
That describes how to set it up, but not really what it does or what it can be used for.

**Comment by ryanrichter94** [comment]
Been a month with no response on clarification, plus made a docs repo issue relating https://github.com/chocolatey/docs/issues/239

**Comment by Chirishman** [comment]
> @Chirishman Are you referring to the LDAP setup documentation here: https://docs.chocolatey.org/en-us/central-management/setup/website#step-4.3-ldap-configuration

Sorry for the late reply. Yes, I opened this a while ago, before that had been written/added. Adding that closes this issue.

**Comment by ryanrichter94** [comment]
Thanks for confirming. We'll be looking to add further detail to the already existing documentation on LDAP with CCM in the near future.
