### ISSUE TITLE
Package Internalizer - Allow to define aliases for internalizer

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-licensed-issues#13]
Currently the internalizer only replaces URL if they are used with certain known Chocolatey helpers. If a package contains a wrapper around a Chocolatey helper the internalizer doesn't know that it would be safe to internalize the resource. An example of this is https://chocolatey.org/packages/KB3033929 which cannot be internalized. The used `Install-WindowsUpdate` helper in the end just calls `Install-ChocolateyPackage` which the internalizer could handle. 

It would be nice if there was the possibility to give the internalizer a list of additional helpers which he should also handle (like `Install-WindowsUpdate` should be treated like a call to `Install-ChocolateyPackage`).

**Comment by ferventcoder** [comment]
Or perhaps the internalizer just seeks out URLs as well as looking for helpers?

**Comment by pascalberger** [comment]
@ferventcoder So that it replaces all URLs? I'm not sure if this is the best solution since this propably will also replace URLs which later don't work. Maybe a setting if he should replace all urls or only for known helpers? And in case of helpers output warnings if there are still some URLs left in the scripts.

**Comment by ferventcoder** [comment]
@pascalberger what urls would not work?

**Comment by ferventcoder** [comment]
Just looking for scenarios here. Are you thinking like something that would implement an old download way of doing things.

**Comment by pascalberger** [comment]
@ferventcoder I was thinking about scripts which are using eg. `System.Net.WebClient`

**Comment by ferventcoder** [comment]
I was as well, how many have you found? Hopefully not very many at all as the validator flags them to be fixed.

**Comment by pascalberger** [comment]
Just stumbled about [this one](https://chocolatey.org/packages/server-jre8). But this is a package which the internalizer anyway cannot handle.

**Comment by ferventcoder** [comment]
How does this look? 

![image](https://user-images.githubusercontent.com/63502/27658394-808ca318-5c15-11e7-859a-38c6caf5fc6b.png)

**Comment by pascalberger** [comment]
👍

**Comment by ferventcoder** [comment]
https://bitbucket.org/chocolatey/chocolicensed/issues/144/ is the tracking for any url `--internalize-all` or `--internalize-all-urls`

Can you follow up with a support email so I can get you a link to play with this feature?

**Comment by ferventcoder** [comment]
Released in 1.12.2
