### ISSUE TITLE
install - Unable to resolve dependencies on INTERNAL Azure DevOps Server using v2 feeds

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#130]
NOTE: This works fine when using Azure DevOps online repositories, it seems to be an issue with an internally deployed Azure DevOps Server only.

### What You Are Seeing?
Attempting to install a package which has dependencies is unable to resolve them

### What is Expected?
Dependencies are found and installed prior to the package

### How Did You Get This To Happen? (Steps to Reproduce)
`choco install git -y` against an internal Azure DevOps Server source is unable to find git.install and subsequent dependencies

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/319)

**Comment by ferventcoder** [comment]
Does this happen all the time? What makes it reproducible? 

Do you see any workarounds?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/1871

It looks like doing the following should work for you: `choco feature disable -n usepackagerepositoryoptimizations`
