### ISSUE TITLE
Central Management - Allow delete computers as a default permission for ccmadmin role

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#133]
Currently one is not able to remove machines from the queue, even if they are no longer being used - without going in and adding that permission directly.

It would be better if we allowed them to remove computers by default.

References
* [Internal Ticket](https://chocolatey.zendesk.com/agent/tickets/6235)
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/304)

**Comment by ferventcoder** [comment]
This is fixed and will be released with Central Management v0.2.0 or whatever is the next version.
