### ISSUE TITLE
Package CDN - Files on CDN with a '+' in the name are not downloaded

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-licensed-issues#134]
When a package contains an installer with a + (and potentially other characters) it cannot be downloaded from the licensed CDN as the + is not escaped to %2B. This results in an error.

### Workaround
Currently, the recommended workaround is to use `--skip-download-cache` should you hit this error.

### References
* [Internal Ticket](https://chocolatey.zendesk.com/agent/tickets/3054)
* [Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/248)

**Comment by ferventcoder** [comment]
This is fixed and will be released in Chocolatey Licensed Extension v2.1.0.
