### ISSUE TITLE
VirusCheck - Spaces are ignored in file path for generic scanner

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#135]
Issue Repro
The setting of genericVirusScannerArgs does not properly set the path to the file to be scanned.
For example we configured the setting like this: choco config set genericVirusScannerArgs "-TestFile [[File]]"
However, when the path to the executable that should be scanned contains a space, it will be incorrectly cut off:
Example: “choco install firefox” will lead to the path “C:\Users\sba\AppData\Local\Temp\chocolatey\Firefox\74.0\Firefox" being passed instead of “C:\Users\sba\AppData\Local\Temp\chocolatey\Firefox\74.0\Firefox Setup 74.0.exe”
We have tried surrounding the [[File]] placeholder with quotes, single quotes, etc. without success.
How could we achieve that the full path gets passed, or is this a bug?

Other Information

Chocolatey.Extension Version - 2.0.3

References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/321)

**Comment by ferventcoder** [comment]
The default will now be `'[[File]]'` and if the configuration has that, it will convert it to `""[[File]]""` and then replace `[[File]]` with the path. That way the behavior is configurable.

**Comment by ferventcoder** [comment]
Edited last comment for clarity

**Comment by ferventcoder** [comment]
This has been completed and will be released with Chocolatey Licensed Extension v2.1.0.
