### ISSUE TITLE
VirusCheck - Timeout of 120 seconds is not configurable

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#136]
Issue Repro
The virus scan seems to have a timeout of 120 seconds which cannot be configured.
Our custom virus scan process sometimes takes several minutes, so we got the following error message with some binaries:
Chocolatey timed out waiting for the command to finish. The timeout
specified (or the default value) was '120' seconds. Perhaps try a
higher --execution-timeout? See choco -h for details.
           The suggested solution does not help, neither does increasing the commandExecutionTimeoutSeconds setting.

           We could not find any related configuration option to increase this specific timeout.

           How can we increase this timeout?

Other Information

Chocolatey.Extension Version - 2.0.3

References
[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/322)

**Comment by ferventcoder** [comment]
This is completed for Chocolatey Licensed Extension v2.1.0. The setting in the config will be `genericVirusScannerTimeoutInSeconds` and will be set to 120 seconds by default.
