### ISSUE TITLE
Central Management - Deleted/Hidden items are still being used for counts for paging purposes in Software

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#139]
It appears as software (maybe computers) are being removed from screens, the counts and paging are not being updated to reflect that.
This could just affect software since we are selecting to only show those that are active on current machines.

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/326)

**Comment by ferventcoder** [comment]
This has been fixed and will be released with the next version of Central Management - likely v0.2.0
