### ISSUE TITLE
choco optimize - Reduce size of current nupkgs in chocolatey/lib folder

### ISSUE THREAD

**Issue by mwallner** [chocolatey/chocolatey-licensed-issues#15]
Having the package-reduce feature available for freshly installed and updated packages in `chocolatey.extension.1.11.1-beta` is great, unfortunately this only works for new installs and updates.
A feature that would allow to 'clean' up existing package installs (remove binary artifacts from nupkgs that are present in pkg/tools anyway) would be nice to have.

**Comment by ferventcoder** [comment]
https://bitbucket.org/chocolatey/chocolicensed/issues/148

**Comment by ferventcoder** [comment]
This is going to be in preview for 1.12.0 - so you will need to ensure you have turned on preview features - `choco feature enable -n allowPreviewFeatures`.

**Comment by ferventcoder** [comment]
![image](https://user-images.githubusercontent.com/63502/27928992-ddf3e574-6256-11e7-8324-c29adb75e543.png)

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/FeaturesPackageReducer#optimize-command

**Comment by AdmiringWorm** [comment]
@ferventcoder Am I correct to assume that this is only available in the business edition of the choco+extension?
I noticed the labels which makes me believe as such, just wanted to be completely sure.

**Comment by ferventcoder** [comment]
All licensed editions for this one.

**Comment by AdmiringWorm** [comment]
ah nice, thanks

**Comment by ferventcoder** [comment]
Thanks for catching that - didn't realize it was not set properly.
