### ISSUE TITLE
Central Management - Service crashes when updating CentralManagementServiceUrl value

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#151]
### What You Are Seeing?

When modifying the configuration for CentralManagementServiceUrl via `choco config`, the service crashes upon the config file being updated.

### What is Expected?

The service gracefully restarts to apply the change

### How Did You Get This To Happen? (Steps to Reproduce)

Install CCM
Change the Service URL value with the Central Management Service running

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/416)

**Comment by ferventcoder** [comment]
This is fixed in Chocolatey Central Management v0.2.0.
