### ISSUE TITLE
Chocolatey.Extension - License file typo

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#159]
### What You Are Seeing?

In LICENSE.txt on line 62 there is a typo. Agreeemnt should be changed to Agreement

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/336)

**Comment by ferventcoder** [comment]
This is fixed for Chocolatey Licensed Extension v2.1.1

**Comment by ferventcoder** [comment]
As this is tiny, it won't be noted as part of the release notes.
