### ISSUE TITLE
Central Management - Deployments - Switching from Basic to Advanced script without providing package name causes validation errors

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#164]
### What You Are Seeing?

If you change the drop-down for a Basic step to a value, change back to
advanced and create a posh script, you cannot save the step until you
change the basic back to Choose command.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Create a deployment
2. Add a deployment step
3. Change script option to "Basic"
4. Change script command to any option other than "Choose Command"
5. Leave the "Package name" field empty
6. Decide that you want to do an advanced, and click on "Advanced"
7. Create a script.
8. Click Save.

[internal issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/427)

**Comment by gep13** [comment]
This is fixed and will be released with CCM v0.3.1.
