### ISSUE TITLE
Central Management - FIPS Compliance

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#167]
### What You Are Seeing?
When using CCM in an environment which is running under FIPS 140, you will see the following error message:

### Output Log
```
ft.AspNetCore.Routing.EndpointMiddleware – Executed endpoint ‘Abp.AspNetCore.Mvc.Proxying.AbpServiceProxiesController.GetAll (Abp.AspNetCore)’
  An unhandled exception has occurred while executing the request
  This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
```

## References

* ZenDesk Support Issues
  * [7487](https://chocolatey.zendesk.com/agent/tickets/7487)
  * [8841](https://chocolatey.zendesk.com/agent/tickets/8841)
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/430)

┆Milestone: 0.5.0

**Comment by ferventcoder** [comment]
### Possible Workaround

```xml
<configuration>
    <runtime>
        <enforceFIPSPolicy enabled="false"/>
    </runtime>
</configuration>
```

**Comment by gep13** [comment]
@ferventcoder we attempted this workaround but it didn't work when testing it out.

**Comment by gep13** [comment]
This will ship as part of Chocolatey Central Management 0.5.0.
