### ISSUE TITLE
Central Management - Service Install - Netsh Entries Incorrectly Parsed ("Cannot index into a null array") when installing in different locales

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#174]
## What You Are Seeing?

When trying to upgrade CCM to v0.3.0 Chocolatey find a single self-signed cert and uses it to continue installation and then errors out saying cannot index into a null array. There is some error in that existingCertificates count is coming back non-empty, but the actual object is still null.

## What is Expected?

When upgrading, Chocolatey should see the self-signed cert and create an SSLEntry based on the cert. 

## References

[ZenDesk Support Issue](https://chocolatey.zendesk.com/agent/tickets/7214)

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/473)

**Comment by gep13** [comment]
This is fixed and will be released with CCM v0.3.1.
