### ISSUE TITLE
Self-Service - Provide information about user which triggered installation

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-licensed-issues#179]
While it is not perfect for a system wide package manager like Chocolatey, some packages require access to user profile for various reasons. One example is markdownlint-cli which installs a node module (see https://github.com/bbtsoftware/chocolatey-packages/issues/96).

These kind of packages are working fine as long as installed with admin permissions. If installed using background service they fail, since background service runs under a different user. To make these packages work with background service it would require the information which triggered the installation available during execution of package installation.

**Comment by ryanrichter94** [comment]
After working through this it look like using `$env:USER_CONTEXT` to get the username of the original user is a workable fix for this.

**Comment by ferventcoder** [comment]
@ryanrichter94 This appears good to close? Does this also link up with an internal issue?

**Comment by ryanrichter94** [comment]
@ferventcoder No internal issue for this one. It's good to close.
