### ISSUE TITLE
problems with remote WINRM commands, and background agents

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/chocolatey-licensed-issues#18]
### What You Are Seeing?

Through a remote PSSession, using WinRM the runspace is unable to access the service due to security restrictions. Due to this, chocolatey is returning an error message advising background service is unreachable.

### What is Expected?

Potentially a better way of handling the error, I understand it needs to be clear that the background service will not be used from remote runspaces, but this looks to cause problems with remoote administration. 

### How Did You Get This To Happen? (Steps to Reproduce)

Enter-PsSession <Remote Computer>

Choco list -l -r

**Comment by ferventcoder** [comment]
@lukemgriffith is this with the new setting enabled (for admins)?

**Comment by lukemgriffith** [comment]
Had a play with this, as an administrator through a remote session still getting the problem.

I can replicate this interactively also, by shutting down the Chocolatey-Agent service and running the same command.

Choco Install bypasses, but Choco List still throws a warning that the background service is unreachable.

**Comment by ferventcoder** [comment]
Choco list should not be attemtping to go through the background service. Elevating this bug

**Comment by lukemgriffith** [comment]
Only reason i could think it might respect it - would be due to the request made to only allow Non-Admins to view self-service repositories? unsure if anything was ever done with that.

**Comment by lukemgriffith** [comment]
ah no, it was this https://github.com/chocolatey/chocolatey-licensed-issues/issues/6
so ignore me :D

**Comment by ferventcoder** [comment]
I have a fix I want you to try out to see if it helps?

**Comment by ferventcoder** [comment]
Released with Chocolatey Licensed Extension v1.12.1. https://chocolatey.org/docs/release-notes-licensed
