### ISSUE TITLE
Package Internalizer - Using --version to choose version to internalize causes dependencies to build with that same version

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#180]
Example:

`choco.exe download --limit-output --Source https://chocolatey.org/api/v2/ --Internalize --version 15.0.18338.0 --downloadCache --Name sql-server-management-studio --force -y --no-progress` causes all nupkgs to be tagged with the version from the command.

## References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/359)

**Comment by steviecoaster** [comment]
This is fixed already here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/44. 

If you are running into this issue, upgrade your licensed extension to 1.12.12 or higher.

**Comment by ferventcoder** [comment]
Duplicate of #44
