### ISSUE TITLE
Central Management - Expose API with Swagger UI documentation

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#183]
The various API methods which are available within CCM, for example:

* Creating a new Group
* Starting a deployment
* etc

Should be exposed in a common format ([Swagger](https://swagger.io/)), along with providing a [Swagger UI](https://swagger.io/tools/swagger-ui/) endpoint for visualizing and interacting with the available methods.

### References

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/442)

**Comment by ferventcoder** [comment]
This is complete and will be released in Central Management v0.4.0.
