### ISSUE TITLE
Chocolatey Extension v1.12.0 breaks Chocolatey GUI

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#19]
### What You Are Seeing?

The GUI dies immediately

![image](https://user-images.githubusercontent.com/63502/28139610-89f5855e-671a-11e7-8bbd-7b1173ca4eea.png)

On further investigation, it was determined to be related to a new configuration class that was not marked serializable.

![image](https://user-images.githubusercontent.com/63502/28139865-7fa13f16-671b-11e7-883b-2d800d526f3a.png)

### What is Expected?

For the GUI to work

### How Did You Get This To Happen? (Steps to Reproduce)

Install Chocolatey Extension v1.12.0 and the latest prerelease of the GUI.

### Referenced Issues

* https://bitbucket.org/chocolatey/chocolicensed/issues/153
* https://github.com/chocolatey/ChocolateyGUI/issues/454

**Comment by AdmiringWorm** [comment]
I found out today when I tried to update my choco packages that this issue doesn't just break Chocolatey GUI, but also throws out this error when calling `choco update`

**Comment by ferventcoder** [comment]
And with packages.config installations.

**Comment by ferventcoder** [comment]
For you - likely for remembered arguments?

**Comment by AdmiringWorm** [comment]
could be, I'll try disabling the feature and check

**Comment by AdmiringWorm** [comment]
yup, disabling `useRememberedArgumentsForUpgrades` makes upgrade working again.
