### ISSUE TITLE
Self-Service - Allow uninstalls for self-service from installations by self-service users

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#2]
Allow users who have installed software via self-service to uninstall the package as well.

https://github.com/chocolatey/choco/issues/1272 was a location this was created

The issue for this is at https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/109

**Comment by ferventcoder** [comment]
If a user can uninstall any package, they could uninstall the Agent service, Chocolatey, and really any package that may be there for reasons not related to the reason you would want a user to be using self-service. This feature request is about allowing users that have installed a package to be able to uninstall it.

There is another feature that would allow an admin to set other commands up for background mode, allowing users to uninstall any package - that has the security concerns mentioned here.

**Comment by asmartin** [comment]
Would the scope of the ticket allow a user to uninstall any package installed from the chocolatey repo? For example, if an admin installs `packagea` version `2.1.0` from the chocolately repo, but then the user on the computer needs to install `packagea` version `1.0.0` for compatibility reasons, could the user then run `choco uninstall packagea` followed by `choco install packagea --version 1.0.0` in background mode to get the version they need?

I wouldn't think this use case would have the security concerns because it is a package that was originally installed from the chocolatey repo, and if there were security vulnerabilities with the old package version it would be the admin's responsibility to just remove it from the repo.

**Comment by ferventcoder** [comment]
@asmartin that is a good scenario, but you can also `choco install packagea --version 1.0.0 --allow-downgrade` to get the same affect. It's one reason why some use cases would need to allow any package uninstall, and that is a secondary feature request we have outstanding to allow admins to add more items to the list of things that could go through background service.

**Comment by ferventcoder** [comment]
@asmartin the new release of chocolatey licensed extension allows you to configure additional commands. Please see the release announcement related to that at https://groups.google.com/forum/#!topic/chocolatey-announce/1K2Hoi559ZI

**Comment by asmartin** [comment]
This looks great, thanks for implementing this!

**Comment by lukemgriffith** [comment]
Is there a chance we could also include only uninstalling a subset of packages, that were installed from a specific source?

**Comment by ferventcoder** [comment]
@lukemgriffith It's open for creation of a feature - I would create it as a new one separate from this though. Do you want to write it up or would you like me to?

**Comment by ferventcoder** [comment]
This is completed for Chocolatey Licensed Extension v2.0.0 and Chocolatey Agent v0.9.0. This should be released in the next week or two.

**Comment by ferventcoder** [comment]
For reference, you will need to add "uninstall" to the allowed background mode commands and then use this feature `allowBackgroundServiceUninstallsFromUserInstallsOnly` to restrict it to just the installs that the user has completed. It is worth noting that a user installing/upgrading will only be able to uninstall what they themselves have installed/upgraded - based on the last action - so if there is an automated back end service that upgrades, it may remove the note of the user, keeping them from uninstalling later.

**Comment by ferventcoder** [comment]
This needs documented.
