### ISSUE TITLE
Automated Chocolatey Log Cleanup

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#214]
## Description
Currently with the way Chocolatey does verbose logging once the logs reach a certain limit new log files get generated in the C:\ProgramData\chocolatey\logs directory. A builtin utility to get rid of these extra logs would be helpful.

### Current Workaround
```
Get-childItem $env:ChocolateyInstall\logs\chocolatey.*.log | Remove-Item -Force
```

Running this bit of Powershell as a scheduled task via whatever deployment/configuration manager available.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed-services/-/issues/72) by [Unito](https://www.unito.io)
┆Milestone: 1.1.0

**Comment by ferventcoder** [comment]
This was b/c sometimes log4net doesn't handle cleanup very well in some situations (naming of files?).
