### ISSUE TITLE
Agent Service - Cannot Upgrade Agent Using CCM

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#222]
### What You Are Seeing?
When running a CCM Deployment to upgrade the chocolatey-agent package the deployment will not run as you run into a chicken and egg scenario where you cannot actively make changes to the agent service while it is running trying to do a CCM deployment. 

### What is Expected?
The agent service should be able to be upgraded via a CCM deployment. Currently the only way to get this to run is manually running a script with the upgrade command on the system locally for each machine or via a configuration manager.

#### References
* [ZenDesk Ticket 1](https://chocolatey.zendesk.com/agent/tickets/11479)
* [ZenDesk Ticket 2](https://chocolatey.zendesk.com/agent/tickets/11697)

**Comment by marcinkubica** [comment]
+1 for the ability to upgrade Chocolatey components via CCM. It's very unusual for a packaging service to require 3rd party solution to upgrade itself.

**Comment by ryanrichter94** [comment]
Closing this issue as we now have documentation on performing an upgrade of the chocolatey-agent package using an advanced deployment within CCM. [Documentation link](https://docs.chocolatey.org/en-us/agent/upgrade#use-chocolatey-central-management-to-upgrade-chocolatey-agent).
