### ISSUE TITLE
Add feature to allow disabling of the This PC source

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#228]
## Feature Request
Would like the option to hide the "This PC" tab from the view in Chocolatey GUI much like how the HideAllRemoteChocolateySources configuration option works. 

### Explanation
This allows for less confusion or need for end-user training for self-service users when navigating the Chocolatey GUI interface. Allowing for a further simplified layout. 

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/10507)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/chocolateygui-licensed/-/issues/20) by [Unito](https://www.unito.io)
┆Milestone: 0.3.0

**Comment by gep13** [comment]
The related Chocolatey GUI issue for creating the feature toggle is here: https://github.com/chocolatey/ChocolateyGUI/issues/859

**Comment by gep13** [comment]
This feature has now been released.

You will need to install Chocolatey GUI v0.19.0 and Chocolatey GUI Licensed Extension v0.3.0 in order to take advantage of it.
