### ISSUE TITLE
Provide ability to see the number of Computers that have specific Software installed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#231]
## Description
When viewing the list of Software packages, it would be good to have another column that lists how many computers have that specific package and version installed.

## Why Is It Needed
To prevent the need for the user to navigate into the details page if/when they are only interested in how many computers have a specific package version installed.

## Related Issues and Tickets
* [Zendesk](https://chocolatey.zendesk.com/agent/tickets/16821)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/620) by [Unito](https://www.unito.io)
┆Milestone: 0.12.0

**Comment by imm0rtalsupp0rt** [comment]
[Zendesk ticket requesting similar and possible expanded functionality](https://chocolatey.zendesk.com/agent/tickets/16821)

**Comment by gep13** [comment]
This has been completed, and will ship as part of Chocolatey Central Management 0.12.0.
