### ISSUE TITLE
Ubiquitous Install Directory - Request for Installer Type Addition

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#234]
### What You Are Seeing?
When running `choco install 1password --install-directory C:\Programs\1password -y` pulling version 7.7.810 i'm getting the following log output with an error regarding Chocolatey being unable to detect the installer type.

### Output Log
```
ERROR: Unable to detect installer type and override install directory. Please remove --install-directory override switch.
The install of 1password was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\1password\tools\chocolateyInstall.ps1'.
 See log for details.
```

### What is Expected?
Is it possible to have this type of executable file referenced in the Chocolatey Licensed Code base to allow for passing `--install-directory` as feature when working with this type of installer. 

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/10848)
* [GitLab Code Reference](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/blob/develop/src/chocolatey/infrastructure/detector/InstallDetectorService.cs#L140-148)

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/505) by [Unito](https://www.unito.io)

**Comment by ferventcoder** [comment]
What's the installer type being used? Custom installers notwithstanding, there is nothing we can do with custom installers (unfortunately).

**Comment by ryanrichter94** [comment]
Went through and attempted to find installer type for this exacutable. Ran through Universal Sient Switch Finder(USSF) as well as other know methods to invoke silent switches in order to find out an installer type. Unable to find installer type so closing issue.
