### ISSUE TITLE
Add feature to allow disabling of "Update All" button in Chocolatey GUI

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#240]
## Feature Request
Add Chocolatey GUI config option to allow greying out of the choco upgrade all button if set. Thus disabling users from running a `choco upgrade all` from Chocolaty GUI.

## References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11151)
* Related [GitHub Issue](https://github.com/chocolatey/chocolatey-licensed-issues/issues/239)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/chocolateygui-licensed/-/issues/21) by [Unito](https://www.unito.io)
┆Milestone: 0.3.0

**Comment by gep13** [comment]
This feature has now been released.

You will need to install Chocolatey GUI v0.19.0 and Chocolatey GUI Licensed Extension v0.3.0 in order to take advantage of it.
