### ISSUE TITLE
Provide ability to create an empty Deployment Plan directly for a specific Computer

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#259]
## Description

Add a new button on the Computer details page to allow creating a new empty deployment that is associated with the computer.

## Why Is It Needed

To make it easier for users to create a new deployments for a specific computer

## Related Issues and Tickets

* [ZenDesk Ticket 1](https://chocolatey.zendesk.com/agent/tickets/11535)
* [ZenDesk Ticket 2](https://chocolatey.zendesk.com/agent/tickets/12173)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/693) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
This has been completed, and it will ship as part of Chocolatey Central Management 0.12.0.
