### ISSUE TITLE
CCM - Sensitive package parameters shown in database & Deployment step page

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#267]
### What You Are Seeing?
When running an advanced deployment within CCM passing `--package-parameters-sensitive` they will be shown as plain text within the View Additional Deployment Step Details view. The sensitive package parameters are also written plain text within the dbo.DeploymentSteps table of the CCM DB. 

### What is Expected?
The sensitive package parameters that get passed in an advanced deployment should be left off or obfuscated where shown & written.

### How Did You Get This To Happen? (Steps to Reproduce)
Mocked up the following advanced deployment step within CCM:
`choco upgrade chocolatey-agent --package-parameters-sensitive="'/Username:MyUsername /EnterPassword=""SuperSecretPassword""'"`

### Screenshots
![image](https://user-images.githubusercontent.com/57045117/134738051-981c747c-b4c8-4a24-a5c8-8f643f8e899d.png)
![image](https://user-images.githubusercontent.com/57045117/134738426-4021c400-85bf-4aa6-a527-10002f77e920.png)

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11650)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/698) by [Unito](https://www.unito.io)
┆Milestone: 0.7.0

**Comment by verzada** [comment]
Just an FYI, there's a typo in the example given:

--package-parameters-sensetive 
instead of 
 --package-parameters-sensitive

The parameters looks like this:

 --install-arguments-sensitive=VALUE
 --package-parameters-sensitive=VALUE
  ref https://docs.chocolatey.org/en-us/choco/commands/upgrade
