### ISSUE TITLE
Chocolatey Agent - Look Into Way of Upgrading the chocolatey-agent via CCM Deployment

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#269]
### Description
Look into having a way to allow for the `chocolatey-agent` package to be upgraded via CCM deployment. 

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/11479)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed-services/-/issues/81) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
Is this a duplicate of this? https://github.com/chocolatey/chocolatey-licensed-issues/issues/222

**Comment by ryanrichter94** [comment]
@gep13 You are correct in this issue is a duplicate of #222. Closing this one
