### ISSUE TITLE
Provide ability to create a Deployment Plan for all outdated packages for a single Computer

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#281]
## Description
When viewing the computer details page to view what outdated packages a certain computer has. It would be really nice to be able to just click an upgrade now button on this screen and have a deployment run a quick choco upgrade for the package in question that is reporting as outdated.

Having an upgrade now modal within this page would make this process much more efficient.

Picture of computer details page for reference: ![image](https://gitlab.com/-/project/7092374/uploads/94e2cd4de6431a464463fb67a3bb7828/image.png)

## Why Is It Needed
Currently you have to go out of this page, add the machine to a deployment group, create a deployment specifying the package id, target group, and Chocolatey command to run. Then clicking through the 3 checks to kick off the deployment to run.

## Related Issues and Tickets
https://chocolatey.zendesk.com/agent/tickets/9221

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/724) by [Unito](https://www.unito.io)
┆Milestone: 0.12.0

**Comment by gep13** [comment]
This has been completed and will ship as part of Chocolatey Central Management 0.12.0.
