### ISSUE TITLE
Central Management API - Allow For Creation of Advanced CCM Deployments Via the API

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#291]
### Request
Currently using the /api/services/app/DeploymentPlans/CreateOrEdit API call. You are only able to specify a basic deployment step of installing, upgrading, or uninstalling a specific package. 

Would like the capability to enter in Powershell to run an advanced deployment instead of just being tied to the options of a basic deployment step. Such as stopping services and other powershell operations.

#### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/12899)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/735) by [Unito](https://www.unito.io)

**Comment by vexx32** [comment]
This feature already exists, though we could definitely use better documentation around it. The essence of it is that it's very similar to a basic step, but you additionally need to set `isPrivileged` to `true` in the given DeploymentStep, and the `script`  property is then interpreted as a full PowerShell script.

Taking the example from our [api examples](https://docs.chocolatey.org/en-us/central-management/usage/api/examples#add-a-deployment-step) for a basic step, it can be modified so the step is considered an Advanced step:

```powershell
$params = @{
    Uri         = "https://$CcmServerHostname/api/services/app/DeploymentSteps/CreateOrEdit"
    Method      = "POST"
    WebSession  = $Session
    ContentType = 'application/json'
    Body        = @{
        deploymentPlanId               = $deployment.Id
        name                           = "Choco Upgrade All"
        validExitCodes                 = "0, 1605, 1614, 1641, 3010"
        executionTimeoutInSeconds      = 14400
        machineContactTimeoutInMinutes = "0"
        failOnError                    = $true
        requireSuccessOnAllComputers   = $false
        deploymentStepGroups           = @(
            @{ groupId = $Group.Id; groupName = $Group.Name }
        )
        # For advanced steps, set IsPrivileged to true, and enter a powershell script as a string
        isPrivileged                   = $true
        script                         = 'Write-Host "This is treated as a PowerShell script"'
    } | ConvertTo-Json
}
$null = Invoke-RestMethod @params
```

**Comment by gep13** [comment]
@vexx32 what are your thoughts on adding this as an example to the examples section that you already linked to?  Seems like a sensible addition to me (with the added caveat regarding permissions that you have also stated here).

**Comment by vexx32** [comment]
Makes sense to me. Should we transfer this to the docs repo?

**Comment by gep13** [comment]
@vexx32 hmm, this is now synced via Unito to another issue, so I don't think moving it is a good idea, no.  I would be more inclined to create a new issue, and link to it from here, and then close this one out.

**Comment by vexx32** [comment]
Duplicated this issue to https://github.com/chocolatey/docs/issues/352, closing this one for now. 🙂
