### ISSUE TITLE
choco and cup throw error about "suitable location for change.exe"

### ISSUE THREAD

**Issue by Godeke** [chocolatey/chocolatey-licensed-issues#30]
I'm adding this here per request by @ferventcoder as this appears to be an issue with the licensed extension. I'm not using the command under RDP, but on a local machine, which does make the reference to choose.exe odd.

### What You Are Seeing?
choco and cup throw error about suitable location for change.exe after upgrade to Fall update for Windows 10. Searching for change.exe I can only find references to a RDP management command.

### How Did You Get This To Happen? (Steps to Reproduce)
Enter either "choco" or "cup" command at admin powershell. Only "choco -h" works as expected (produces help output).

### Output Log
> choco
Chocolatey v0.10.8 Professional
Please run 'choco -?' or 'choco <command> -?' for help menu.
The registered delegate for type IEnumerable<ITask> threw an exception. Unable to find suitable location for change.exe. Searched the following locations: 'C:\WINDOWS\SysNative\change.exe; C:\WINDOWS\System32\change.exe'

**Comment by ferventcoder** [comment]
This will be fixed in 1.12.8. You may need to rollback to a previous version first.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/1432

**Comment by ferventcoder** [comment]
For this specific fix, you may want to go to https://chocolatey.org/docs/installation-licensed#unable-to-load-licensed-version-extensions-and-commands and follow the steps here once 1.12.8 is released (in a few minutes).

**Comment by ferventcoder** [comment]
https://groups.google.com/forum/#!topic/chocolatey-announce/3rRC964L0SI

**Comment by Godeke** [comment]
I can confirm the fix worked with the instructions found at https://chocolatey.org/docs/installation-licensed#unable-to-load-licensed-version-extensions-and-commands (removing the extension and configuration and restoring it).
