### ISSUE TITLE
Add the ability to send email notifications when a Deployment Plan has finished

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#328]
## Is Your Feature Request Related To A Problem? Please describe.
Would like the ability to receive an email notification of a deployments final state. To tell if a deployment succeeded or failed without needing to log in to the webpage to check the final state of a deployment. 

## Describe The Solution. Why is it needed?
Having email notification of deployment state is desired by some of our customers. Also makes monitoring easier. If for say I have a daily upgrade all. I get an email daily to tell me if the deployment was successful or not without having to login and check daily in the web dashboard. 

## Additional Context.
N/A

## Related Issues
N/A

## References:
- [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/15824)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/792) by [Unito](https://www.unito.io)

**Comment by gep13** [comment]
The functionality requested here is now available in Chocolatey Central Management 0.11.0.
