### ISSUE TITLE
Chocolatey Licensed Extension does not fall back to open source behaviour when license verification fails

### ISSUE THREAD

**Issue by spncrgr** [chocolatey/chocolatey-licensed-issues#330]
### What Are You Seeing?
Executing a Chocolatey command, including utility commands, results in a `SimpleInjector.ActivationException` being thrown.

### What is Expected?
The Chocolatey CLI should display the license invalid or missing message and not throw an error.

### How Did You Get This to Happen? (Steps to Reproduce)
1. place an expired license file in the folder at `$env:ChocolateyInstall\license`
1. Run a `choco` command. I ran `clist -l`.

### System Details
* OS Build: 10.0.19044.0
* Windows PowerShell version: 7.3.0
* Chocolatey version: 1.2.0

### Output Log
https://gist.github.com/spncrgr/1605519b4c174b61702daf0da1812b3a

![20221123 Chocolatey CLI Error](https://user-images.githubusercontent.com/360099/203595412-50d2127c-d8bf-417d-909d-71e6d43a337f.gif)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/649) by [Unito](https://www.unito.io)
┆Milestone: 5.0.1

**Comment by pauby** [comment]
I confirm the error appears with an expired Business license, but does not appear with an expired Professional license.

![image](https://user-images.githubusercontent.com/12760779/203605134-2d38c5bc-1397-4334-b114-dc66624f7984.png)
