### ISSUE TITLE
Provide ability to duplicate a Deployment Step within a Deployment Plan

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/chocolatey-licensed-issues#332]
## Description
While on a support call with a Customer we were working through drafting a recurring deployment where we were setting up deployment steps to upgrade certain apps. While doing this I thought being able to duplicate a deployment step while you are drafting out a deployment would make this process a lot less tedious. 

## Why Is It Needed
I think having the ability to duplicate a deployment step you just created while drafting a deployment would be helpful. As well as making the process potentially far less tedious for deployments that have several basic steps where only possibly the package name is changed but the target and other settings in that step would be the same.

## Related Issues and Tickets
N/A

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/795) by [Unito](https://www.unito.io)
┆Milestone: 0.12.0

**Comment by gep13** [comment]
This has been completed, and will ship with version 0.12.0 of Chocolatey Central Management.
