### ISSUE TITLE
Add an item to the Dashboard page to show the number of Computers that have not recently reported into Chocolatey Central Management

### ISSUE THREAD

**Issue by imm0rtalsupp0rt** [chocolatey/chocolatey-licensed-issues#335]
### Checklist
* [x] I have verified this is the correct repository for opening this issue.
* [x] I have verified no other issues exist related to my request.

### Describe The Solution. Why is it needed?
Place a Key Performance Indicator (KPI) on the Dashboard of Chocolatey Central Management that would tell how many agents have not checked in in a specified, configurable time frame that can be set in the Settings UI. Clicking on this KPI would then take users to the Computers page.

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/central-management/choco-licensed-management-ui/-/issues/796) by [Unito](https://www.unito.io)
┆Milestone: 0.12.0

**Comment by gep13** [comment]
This has been completed and will be shipped with Chocolatey Central Management 0.12.0.
