### ISSUE TITLE
Changes to the list parameter not understandable

### ISSUE THREAD

**Issue by threechord82** [chocolatey/chocolatey-licensed-issues#348]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

We run an internal repo which we keep up to date using the updatescript. (https://docs.chocolatey.org/en-us/guides/organizations/automate-package-internalization#script-update-prodrepofromtest.ps1)
Unfortunately, this script is no longer executable with the rollout of version 2.0.

It doesn't matter if I use the name of the internal repo or the address. I get the statement every time: 
"choco list --source $TestRepo --all-versions --limit-output
When using the '--source' option with the 'choco list' command, only a named alternative source can be provided."

It doesn't matter if I enter the address of the source in the variable (https://xxxx.yyyyyy.zzz/repository/choco-hosted/) or the name I gave to the source (choco_internal).

Unfortunately, the help in this regard does not really provide an explanation of how the command must now be. 

### What is Expected?

I expected the updatescript to be still functional

### How Did You Get This To Happen?

I run the script daily (with variables set, of course). But since the update to version 2.0 this script does not run anymore

### System Details

* Operating System: 10.0.17763.0
* Windows PowerShell version: 5.1.17763.3770 
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version: Chocolatey v2.0.0 Business
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
N/A
```

### Output Log

```bash
Chocolatey had an error occur:
System.ApplicationException: When using the '--source' option with the 'choco list' command, only a named alternative source can be provided.
   bei chocolatey.infrastructure.app.commands.ChocolateyListCommand.Run(ChocolateyConfiguration config)
   bei chocolatey.licensed.infrastructure.app.commands.ProChocolateyListCommand.#=zFy_ZTe9J$E85AE1jCA==.#=zoTHROGpJL1HsaRJa3Q==()
   bei chocolatey.licensed.infrastructure.app.utility.BackgroundServiceUtility.Run(LicensedChocolateyConfiguration configuration, Action originalRunAction)
   bei chocolatey.infrastructure.app.runners.GenericRunner.Run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   bei chocolatey.infrastructure.app.runners.ConsoleApplication.Run(String[] args, ChocolateyConfiguration config, Container container)
   bei chocolatey.console.Program.Main(String[] args)
```

**Comment by pauby** [comment]
There is a [sticky issue](https://github.com/chocolatey/chocolatey-licensed-issues/issues/347) which points to the upgrade guide. Specifically, see the [changes to `choco list`](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#the-list-command-now-lists-local-packages-only-and-the-local-only-and-lo-options-have-been-removed).

> While the choco list command is still used to query [alternative sources](https://docs.chocolatey.org/en-us/choco/commands/install#alternative-sources), it cannot be used to query remote sources. Please use choco search instead. For example, if you used choco list --source="'<SOURCE URL>'", you should use choco search --source="'<SOURCE URL>'" instead.

Thanks for pointing out the issues with our docs. I'll get them amended just now.

**Comment by threechord82** [comment]
Thanks for the quick reply. That solves my problem already.

**Comment by pauby** [comment]
I've submitted a [PR to update the docs](https://github.com/chocolatey/docs/pull/740), just now.
