### ISSUE TITLE
Obtain Silent Arg Strings outside of Package Creation

### ISSUE THREAD

**Issue by darksidemilk** [chocolatey/chocolatey-licensed-issues#359]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Currently, a licensed user can use `choco new` or the chocolatey package builder via explorer context menu to have choco attempt to get the silent args for a given LOCAL file and make a package from it.

I would like to be able to use just the silent arg parsing on its own. Whether that be using a choco context menu option, a choco command, or a powershell helper function.

### Describe The Solution. Why is it needed?

Having the modular ability to obtain silent arg strings could reduce repeated tasks and improve on CI/CD workflows.
If we are using an internal asset repository like a proget asset repo or a nexus blob store (I believe that's what its called there, we use proget) to store install files that are referenced in choco packages, you can end up creating many copies of what are sometimes very large install files when you only need it in one place at a url.

Ideally, we'd be able to reference the installer at a web url or a local file path to obtain the silent arg string.
We could then create a package and reference the uninstall string in the packageArgs or provide that in the choco package builder gui while referencing the url in that same gui. 

Internally our process is 
* creating a local version of a package with choco new
* upload the install files to our assets repo
* remove the embedded file from the package/replace with .ignore file
* edit the chocolateyinstall.ps1 to reference $url instead of file/filelocation and edit it to use install-chocolateyPackage instead of install-chocolateyinstallpackage

It would be nice to be able to just make an internal package by referencing the install file at a url or something similar to that. 
I realize we can achieve some of this with templates in choco new but as far as I have found we need to make a full local package with files embedded in order to use the auto silent arg grabber.

**Comment by gep13** [comment]
@darksidemilk thanks for reaching out!

If I have understood the issue correctly, I think I have a solution that will reduce the number of repeated steps.

Rather than doing this:

- creating a local version of a package with choco new
- upload the install files to our assets repo
- remove the embedded file from the package/replace with .ignore file
- edit the chocolateyinstall.ps1 to reference $url instead of file/filelocation and edit it to use install-chocolateyPackage instead of install-chocolateyinstallpackage

Do the following:

- Upload the install files to our assets repo
- Run `choco new --url=<url_to_asset_in_repo> --use-original-location`
- A new Chocolatey package will be generated without embedding the file, and it will point to the original location in the asset repo

If this isn't what you are looking for, or if I have misunderstood something, let me know.

**Comment by darksidemilk** [comment]
Well then I misunderstood how it worked, I remembered reading that the silent install args grabber only worked for when the file was local, but at the time we wanted the file to be local.
I gave this a try and it did indeed work. Thank you very much!

I think it would still be a nice to have to be able to get just the silent args with a separate command but this technically solves the bulk of my problem.

Thanks,
-JJ

________________________________
JJ Fullmer
Senior IT Systems Engineer
[Arrowhead Dental Laboratory]
Email   ***@***.******@***.***>
Phone   (801) 572-7253<tel:+1(801)%20572-7253>
Web     arrowheaddental.com<https://www.arrowheaddental.com>
________________________________
[Facebook] <https://www.facebook.com/ArrowheadDentalLab>        [Instagram]  <https://www.instagram.com/arrowheaddentallab/>    [YouTube]
CONFIDENTIALITY NOTICE:
This e-mail, including any attachments, may contain confidential information which is intended only for the use of the individual(s) or entities named.
If you receive this e-mail message in error, please immediately notify the sender by e-mail and delete it.
Dissemination, forwarding, printing or copying of this e-mail without prior consent of the sender is strictly prohibited.
________________________________
From: Gary Ewan Park ***@***.***>
Sent: Wednesday, October 4, 2023 10:11 AM
To: chocolatey/chocolatey-licensed-issues ***@***.***>
Cc: JJ Fullmer ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [chocolatey/chocolatey-licensed-issues] Obtain Silent Arg Strings outside of Package Creation (Issue #359)


@darksidemilk<https://github.com/darksidemilk> thanks for reaching out!

If I have understood the issue correctly, I think I have a solution that will reduce the number of repeated steps.

Rather than doing this:

  *   creating a local version of a package with choco new
  *   upload the install files to our assets repo
  *   remove the embedded file from the package/replace with .ignore file
  *   edit the chocolateyinstall.ps1 to reference $url instead of file/filelocation and edit it to use install-chocolateyPackage instead of install-chocolateyinstallpackage

Do the following:

  *   Upload the install files to our assets repo
  *   Run choco new --url=<url_to_asset_in_repo> --use-original-location
  *   A new Chocolatey package will be generated without embedding the file, and it will point to the original location in the asset repo

If this isn't what you are looking for, or if I have misunderstood something, let me know.
