### ISSUE TITLE
Renaming the computer object in chocolatey central management when the hostname was changed

### ISSUE THREAD

**Issue by pLeXwithFleX** [chocolatey/chocolatey-licensed-issues#370]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Currently the computer object name on central management is not changing when the hostname was changed. The computer is not clearly to identified.

### Describe The Solution. Why is it needed?

When the chocolatey agent is polling, it could send and compare / update the computer object name.

**Comment by pauby** [comment]
@pLeXwithFleX this isn't a feature, but a bug. Can you use the bug template for this issue as it will ask for all the information we need to gather?

**Comment by pLeXwithFleX** [comment]
okay, I try again.
