### ISSUE TITLE
Chocolatey GUI missing Update All button in This PC source when running Chocolatey GUI Extension

### ISSUE THREAD

**Issue by imm0rtalsupp0rt** [chocolatey/chocolatey-licensed-issues#395]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

When running the Chocolatey GUI with the Chocolatey GUI Extension, there should be an Update All button in the upper right hand corner of the GUI near the Check Outdated Packages button when viewing the "This PC" source. This button still appears *without* the GUI Extension, but not *with* it.

### What is Expected?

The Update All button should be present in both licensed and non-licensed Chocolatey GUI.

### How Did You Get This To Happen?

1. Open non-licensed Chocolatey GUI and select the This PC source.
2. Notice the presence of the Update All button.
3. Install the Chocolatey GUI Extension package.
4. Open licensed Chocolatey GUI and select the This PC source.
5. Notice the lack of the Update All button.

### System Details

* Operating System: Windows Server 2019
* Windows PowerShell version: 5
* Chocolatey CLI Version: 1.3.1
* Chocolatey Licensed Extension version: 5.0.2
* Chocolatey License type: Business

### Installed Packages

```bash
Chocolatey GUI 1.1.2
Chocolatey GUI Extension 1.0.2
```

### Output Log

```bash
N/A
```

### Additional Context

Gary and I met for a troubleshooting session around this issue and we discovered that there *is* a workaround, however cumbersome it may be. The following steps were successful in making the Update All button appear.

1. Delete the Config folder from `C:\ProgramData\Chocolatey GUI` and the `data.db` file found in the `C:\Users\<USER>\AppData\Local\Chocolatey GUI` folder.
~~2. Recreate the Config folder in the `C:\ProgramData\Chocolatey GUI` directory. Chocolatey GUI should create this folder at startup, but we found that it did not.~~. Since Chocolatey GUI 2.2.1, this step is no longer required.
3. Start Chocolatey GUI.
4. Once Chocolatey GUI has started, go to Settings.
5. Toggle the `Hide All Remote Chocolatey Sources` setting to ON and then click the Back button.
6. Close and reopen Chocolatey GUI, and go to Settings.
7. Toggle the `Hide All Remote Chocolatey Sources` setting to OFF and then click the Back button.
8. Close and reopen Chocolatey GUI, and go to Settings.
9. Toggle the `Prevent Usage of Update All Button` setting to ON and then click the Back button.
10. Close and reopen Chocolatey GUI, and go to Settings.
11. Toggle the `Prevent Usage of Update All Button` setting to OFF and then click the Back button.
12. The Update All button should now be visible at the upper-right of Chocolatey GUI.

**Comment by gep13** [comment]
When testing this, it was necessary to first reset things back to the beginning, which meant clearing out the following locations:

```
C:\ProgramData\Chocolatey GUI\Config\data.db
C:\Users\<username>\AppData\Local\Chocolatey GUI\data.db
```

**Comment by gep13** [comment]
@imm0rtalsupp0rt after moving this issue to this repository, I expected/wanted the syncing that we have in place to kick in, and do what is necessary, however, this hasn't worked, for "reasons".

I am going to close and re-create this issue, so that the syncing kicking in.  Apologies about the noise.

**Comment by gep13** [comment]
New issue created here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/396
