### ISSUE TITLE
Disable choco download for non-administrators

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#4]
From @lukemgriffith at https://github.com/chocolatey/choco/issues/1299

* https://bitbucket.org/chocolatey/chocolicensed/issues/133/allow-locking-down-commands-to-admin-only

### What You Are Seeing?
Ability to use Choco Download, as a business, non-administrative user from a non-selfservice authenticated repository. 

### What is Expected?
Ideally not to be able to download from non-selfservice (potentially authenticated only), as we want to keep our nupkgs away from users - or the ability to disable the download command. 

### How Did You Get This To Happen? (Steps to Reproduce)

Configured an authenticated repository, without allowing self-service and run choco download on a package, and hte source

### Output Log

```
[15:41:57][+2] D:\git\SSLTests
 ? choco source list
Chocolatey v0.10.5 Business
...
...
bob - https://<Redact>/ChocolateyRepo/nuget (Authenticated)| Priority 0|Bypass Proxy - False|Self-Service - False.


[15:39:31][+2] D:\git\SSLTests
 ? choco download Atom -s bob --ignoredependencies
Chocolatey v0.10.5 Business
Downloading existing package(s) to D:\git\SSLTests\download

Progress: Downloading Atom 1.15.0... 82%
Progress: Downloading Atom 1.15.0... 100%

Atom v1.15.0

Package downloaded to 'D:\git\SSLTests\download\Atom'
```

**Comment by ferventcoder** [comment]
Let me try to understand this better.

If the package is installed, how do you keep the user from seeing the contents? Are you removing access to the lib folder as well from non-admins? Or would you like to (this is highly likely to affect `choco list -lo` until we can get everything running through self-service)?

**Comment by lukemgriffith** [comment]
At the moment we install from a URL, and clean the choco tmp directory on a regular schedule. We try not to keep any binaries in the lib folder.

Essentially we're trying to limit any user having access to certain  binaries that are not in their expected locations (IE after an install) 

With this approach we have a tricky situation with the double hop problem, and accessing the URL that contains our software via remote sessions, at the moment we roll anonymous but for the more sensitive stuff we need to lock it down. Currently our thinking is an authenticated NuGet repo, and embedding the software inside nupkg, using the choco config credentials to bypass double hop - although the downloader has put a spike in the works.

Alternatively prahaps im approaching this from the wrong way, do you have any other ideas? I've been looking at mutual certificate authentication but it seems to add a lot of complexity.

**Comment by ferventcoder** [comment]
@lukemgriffith would it be best to hop on a quick chat to better understand requirements?
https://zoom.us/j/221129959

**Comment by lukemgriffith** [comment]
is it known if this will make the 0.10.6 release?

**Comment by ferventcoder** [comment]
@lukemgriffith This will be in the chocolatey.extension, not in the open source version. It will likely be in Chocolatey.Extension v1.10 (vNext). HTH

**Comment by lukemgriffith** [comment]
Is there a estimated date for 1.10.? 
cheers.

**Comment by ferventcoder** [comment]
@lukemgriffith this upcoming week if all goes well.

**Comment by ferventcoder** [comment]
This is complete for 1.10 

![image](https://user-images.githubusercontent.com/63502/26861350-df22a882-4b08-11e7-83ff-a64c48b4f6e2.png)

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/wiki/ReleaseNotesLicensed#1100-june-9-2017
