### ISSUE TITLE
Self-Service - Timeout after 10 minutes

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#41]
The default receiveTimeout for a netNamedPipeBinding in WCF is 10 minutes. When you have a large package (i.e. working with a multiple GB file) it is very easy to run over this 10 minutes.

It should be possible to change this value, based on the existing execution timeout variable. That way, only one thing needs to be changed.

**Comment by ferventcoder** [comment]
This has been resolved and will be released with Chocolatey Agent (chocolatey-agent) v0.8.2.
