### ISSUE TITLE
PackageInternalizer - Incorrect version number generated for dependent packages

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#44]
Steps to reproduce:

`choco download solr --version 6.5.1 --internalize`

The version number 6.5.1 is passed through when packing the dependencies as well. As a result, the installation fails, as the required version number for the dependency is not there.

Running choco pack again against the generated package files correctly generates the dependency version number.

**Comment by ferventcoder** [comment]
This has been fixed and will be released with Chocolatey Licensed Extension v1.12.12.
