### ISSUE TITLE
PackageBuilder - Installer version overrides package version specified on the command line

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-licensed-issues#46]
When running:

`choco new googlechrome --file=https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi --removearchitecture --buildpackage packageversion=1.0.0`

OR

`choco new googlechrome --version 1.0.0 --file=https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi --removearchitecture --buildpackage`

The .nuspec file that is created has a `<version>` field of `67.81.87`. It would be expected it would have `1.0.0` as specified on the command line.

┆Issue is synchronized with this [GitLab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/405) by [Unito](https://www.unito.io)
┆Milestone: 2.2.x

**Comment by ttdgcp** [comment]
Thanks @pauby. Let me know if I can provide any additional information.

**Comment by thoscut** [comment]
I'm experiencing the same issue, 
Is there any workaround, without involving manual modifications of the nuspec, or an ETA for the bugfix?

**Comment by gep13** [comment]
This issue is actually duplicate by this issue:

https://github.com/chocolatey/chocolatey-licensed-issues/issues/203

So I am going to go ahead and close this one out, as the latter contains more information, including a log file, about the problem.
