### ISSUE TITLE
uninstall - chocolatey unable to uninstall from programs and features

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-licensed-issues#48]
### What You Are Seeing?
I was trying to uninstall a program that had been registered in the programs and features by using `choco uninstall lastpass --fromprograms`. However somehow it didn't manage to uninstall the program, even though it was correctly detected in the registry.
Choco also seems to not being able to detect the application folder (although it do exist). The uninstall display name contains non-ansi character, which maybe could be the problem (I don't really know).

### What is Expected?
Expects chocolatey to be able to uninstall the found programs in the programs and features.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Use one of the following options:
  a. Install the chocolatey package `lastpass`
  b. Install it manually from the lastpass webpage: (https://lastpass.com/misc_download2.php)
1. Try uninstalling it with `choco uninstall lastpass --fromprograms`

### Output Log
https://gist.github.com/AdmiringWorm/8998e1703a6ba07b34e5dd0b6836e033

The following is also a dump of the registry keys found for the lastpass application
https://gist.github.com/AdmiringWorm/f1895e707e10818d94f7ca3d8dfffb4f

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/403) by [Unito](https://www.unito.io)

**Comment by ferventcoder** [comment]
@AdmiringWorm your gists do not resolve.

**Comment by AdmiringWorm** [comment]
@ferventcoder I had somehow deleted the gists that was at those links by a mistake, I've updated with new links now

**Comment by corbob** [comment]
This was difficult to reproduce initially. It seems that Lastpass has changed the installer on their website, and that reproduction step no longer works. However the lastpass package installs an older one that does exhibit this issue.

This is actually an issue in the AutomaticUninstallService of Chocolatey Open Source. When the InstallLocation in the Registry is quoted, we use the FileSystemService to check if it exists. When it's quoted the FileSystemService reports that it doesn't exist even when it does.

I'll open an issue on open source Chocolatey and get a PR up for this tomorrow assuming I don't find any other existing issues.

**Comment by corbob** [comment]
Issue on Open Source Chocolatey created for this: https://github.com/chocolatey/choco/issues/2336

**Comment by corbob** [comment]
Setting this to Review, I'm 85% sure this is completed, just need to confirm it's been added to manual and/or automated tests.

**Comment by corbob** [comment]
Confirmed there's a Manual test for this, and it's marked as released in choco open source where the underlying issue was.
