### ISSUE TITLE
Package Upload - Unable to push to a non https source

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#49]
By default, when pushing to anything other than `localhost` Chocolatey requires that an https address is used.

When an attempt is made to push to say `http://chocolatey/chocolatey`, Chocolatey will return:

```
WARNING! The specified source 'http://chocolatey/chocolatey' is not secure.
 Sending apikey over insecure channels leaves your data susceptible to
 hackers. Please update your source to a more secure source and try again.

 Use --force if you understand the implications of this warning or are
 accessing an internal feed. If you are however doing this against an
 internet feed, then the choco gods think you are crazy. ;-)

NOTE: For chocolatey.org, you must update the source to be secure.
```

When using the Package Upload UI, there is no mechanism to get around this, and instead, the following is shown:

![image](https://user-images.githubusercontent.com/1271146/45951995-7c6dc580-bffd-11e8-8092-08c10e07872a.png)

Package Upload UI should include a mechanism to force the push, which is the equivalent of doing `--force` at the command line.

**Comment by gep13** [comment]
This issue has been resolved, and will be included in the next release of the Chocolatey Licensed extension.

**Comment by ferventcoder** [comment]
That version is Chocolatey Licensed Extension v2.0.0 set to release soon.
