### ISSUE TITLE
Package Upload: Automatically populate the Source Dropdownlist

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#50]
Potential options:

* Simply select the first source in the list (could be if there is only 1 source available, that this is automatically selected)
* Pick the highest priority source based on the property of each source
* Automatically populate with the source that was used last

Selecting based on source priority seems like the best suggestion.

**Comment by ferventcoder** [comment]
@gep13 the sources for pushing are from the apikeys that are saved, not the source list itself as the push URL may differ from the package operations url (where the sources are listed). So curious on some of this?

**Comment by gep13** [comment]
@ferventcoder you are absolutely correct.

In the absence of a priority which can be used to decide which source to select by default, I think the best fallback would be to persist the selected source, and then place that back as the default selection when re-starting the application.

This can be implemented in the same way as we do in Chocolatey GUI using LiteDB.

**Comment by gep13** [comment]
This issue has been resolved, and will be included in the next release of the Chocolatey Extension.
