### ISSUE TITLE
Self-Service - Background Service does not pass the exit code back to the console

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-licensed-issues#51]
### What You Are Seeing?

When installing a package from the command line using choco.exe, with the background service enabled, the install does not pass the exit code back to the choco.exe run from the command line. With the background service disabled the exit code is picked up from the install and choco.exe exits with that code.

### What is Expected?

That choco.exe exit with the exit code returned from the package install with the background service enabled or disabled.

### How Did You Get This To Happen? (Steps to Reproduce)

Create a package that uses `Set-PowerShellExitCode 42` and install it using choco.exe with the background service enabled and then with is disabled.

**Comment by ferventcoder** [comment]
References 
* https://gitlab.com/chocolatey/collaborators/choco-licensed-services/issues/21
* https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/246

**Comment by ferventcoder** [comment]
This is complete and will go out with the next versions of Chocolatey Licensed Extension and Chocolatey Agent.
