### ISSUE TITLE
Notice - Chocolatey Central Management being available for customers

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-licensed-issues#54]
Keep customers notified of the availability of Chocolatey Central Management features, options and environments. Subscribe to the ticket to receive updates.

**Comment by ferventcoder** [comment]
So I see this as only vagrant environments - everything else would follow normal announce methods. Am I correct in this understanding? cc @gep13

**Comment by ferventcoder** [comment]
Vagrant environments, docker environments, etc.

**Comment by gep13** [comment]
As announced here:

https://groups.google.com/forum/#!topic/chocolatey/k_qELX9j73w

Version 0.1.0 of Chocolatey Central Management is now available to Chocolatey for Business Customers.

**Comment by ferventcoder** [comment]
I believe this is closable?
