### ISSUE TITLE
Administrator-only repositories

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-licensed-issues#6]
This is a request to have repositories that are administrator only repositories. These would effectively be invisible to a non-administrative user.

**Comment by lukemgriffith** [comment]
Any potential road map for this feature?

**Comment by ferventcoder** [comment]
It's coming - probably in the next release or two.

**Comment by ferventcoder** [comment]
The FOSS support side of this is now complete - https://github.com/chocolatey/choco/issues/1265

**Comment by ferventcoder** [comment]
This is completed for Chocolatey.Extension 1.12.2
