### ISSUE TITLE
Central Management - Error while installing chocolatey-management-web

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [chocolatey/chocolatey-licensed-issues#62]
Hi,

I'm trying to install the chocolatey central management. When I execute the last installation 
(`choco install chocolatey-management-web --version 0.1.0-beta-20181009`) I receive an error: `System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

Choco.exe is installed in c:\choco so the length isn't that extreme.

Any ideas?

## Referenced Issues
* [Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/106)
* [ZenDesk](https://chocolatey.zendesk.com/agent/tickets/3733)

**Comment by gep13** [comment]
Can you confirm what operating system you are attempting to install onto?

**Comment by thijsvanbloemendaal** [comment]
Windows 2016 Gary!



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Gary Ewan Park <notifications@github.com>
Datum: 01-03-19 23:27 (GMT+01:00)
Aan: chocolatey/chocolatey-licensed-issues <chocolatey-licensed-issues@noreply.github.com>
Cc: thijsvanbloemendaal <thijs_bloemendaal@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [chocolatey/chocolatey-licensed-issues] Error while installing chocolatey-management-web (#62)


Can you confirm what operating system you are attempting to install onto?

**Comment by gep13** [comment]
@thijsvanbloemendaal can I get you to raise a support ticket directly, as this will be the best way to move forward with this.  Thanks.

**Comment by ferventcoder** [comment]
@gep13 what came out of this? Please triage this ticket. Thanks!

**Comment by gep13** [comment]
@ferventcoder I have updated this ticket with links to the associated ticket and issue.

**Comment by gep13** [comment]
This is completed to be released with CCM v0.1.1
