### ISSUE TITLE
PackageInternalizer - UseOriginalLocation switch being appended inappropriately

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#64]
## Issue Repro

`choco download octopusdeploy.tentacle --internalize --internalize-all-urls --output-directory C:\temp\Octopus`

`choco install octopusdeploy.tentacle -y -s C:\temp\Octopus`

Package fails to install with the following error message:

```
ERROR: Cannot bind argument to parameter 'packageName' because it is an empty string.
The install of octopusdeploy.tentacle was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\OctopusDeploy.Tentacle\chocolateyInstall.ps1'
See log for details.
```
Manually fixing the package by removing -UseOriginalLocation from chocolateyInstall.ps1 and generating a new nupkg and then installing the software is successful.

## Other Information

* Chocolatey Version - 0.10.12
* Chocolatey.Extension Version - 1.12.12

**Comment by ferventcoder** [comment]
We've fixed this for release in Chocolatey Licensed Extension v2.0.0.
