### ISSUE TITLE
VirusTotal - 200mb+ unrecognized binaries should not attempt virus scanning

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/chocolatey-licensed-issues#65]
### What You Are Seeing?
When I try to install a package which downloads a large binary - for example `docker-desktop`

* I am met with an error that virus scanning can't be done on packages over 500mb and the install fails.
### What is Expected?
I would expect choco to know this limit and either prompt me with a `y/n` to continue, not fail out completely and force me to re-run the command with `--skip-virus-check`

### How Did You Get This To Happen? (Steps to Reproduce)
`cinst docker-desktop -y`

### Output Log
~~~
C:\WINDOWS\system32> cinst docker-desktop -y
Chocolatey v0.10.12-beta-3-gb65f586 Professional
Installing the following packages:
docker-desktop
By installing you accept licenses for the packages.
Progress: Downloading docker-desktop 2.0.0.3... 100%

docker-desktop v2.0.0.3 [Approved]
docker-desktop package files install completed. Performing other installation steps.
Downloading docker-desktop
  from 'https://download.docker.com/win/stable/31259/Docker%20for%20Windows%20Installer.exe'
Using download CDN cache instead of original url.
Progress: 100% - Completed download of 'Docker for Windows Installer.exe' (540.78 MB).
Download of 'Docker for Windows Installer.exe' (540.78 MB) completed.
Virus scan engines indicate this file has not been scanned before.
ERROR: The virus scanner cannot handle files over 500MB. 'Docker for Windows Installer.exe'
 cannot be verified by the scanner. You must determine if it is safe
 outside of choco and then to install with choco you will need to
 pass --skip-virus-check to install this package.
The install of docker-desktop was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\docker-desktop\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures

* docker-desktop (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\docker-desktop\tools\chocolateyinstall.ps1'.
 See log for details.
~~~

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/397) by [Unito](https://www.unito.io)
┆Milestone: 4.2.0

**Comment by ferventcoder** [comment]
What version of the Chocolatey Licensed extension do you have?

**Comment by ferventcoder** [comment]
We likely need to reduce that limit as VT also reduced their limit to 200MB.

**Comment by bc3tech** [comment]
![image](https://user-images.githubusercontent.com/1967433/54407593-cda96880-46b4-11e9-957d-20f3f84a0afd.png)

**Comment by tomlaf** [comment]
One other option is to have a way to say to Choco, if VT fail (what ever the reason except it a virus) do this : 
- Block the install
- Allows the install
- Complete the VirusScan with genericVirusScannerPath

**Comment by mkevenaar** [comment]
I have the same issue with Chocolatey 0.10.15 / Extension 2.0.2
