### ISSUE TITLE
CentralManagement - Add alias for Install JSON Cmdlet

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-licensed-issues#71]
In the beta version of Chocolatey.Extension, there was a Cmdlet named `Install-ChocolateyAppSettingsJsonFile` and this was used in the 0.1.0-beta-20181009 release of the CCM components.  In the final released version of the Chocolatey.Extension, this was renamed to `Install-AppSettingsJsonFile`.

As a result, the CCM beta no longer works with the released version of Chocolatey.Extension.  This will be corrected once the next release of the CCM components is completed, however, to ensure backwards compatibility, an alias for the alternative name for the Cmdlet should be added.

**Comment by ferventcoder** [comment]
This was completed and will be released with Chocolatey Licensed Extension v2.0.1.
