### ISSUE TITLE
Choco - Exception calling "start" with "0" arguments

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#72]
### What You Are Seeing?
When launching a chocolatey install for a package which references content on a UNC path, arguments are not passed appropriately. 

This is displayed in the log file:

2019-02-15 20:07:42,173 8160 [ERROR] - ERROR: Exception calling "Start" with "0" argument(s): "The directory name is invalid" 

I believe this is due to the use of Get-Directory to find the path.

### What is Expected?
Chocolatey enumerates the UNC correctly to install the package

### Output Log

2019-02-15 20:07:42,173 8160 [ERROR] - ERROR: Exception calling "Start" with "0" argument(s): "The directory name is invalid" 

### References:

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/274)

**Comment by ferventcoder** [comment]
I believe this is a choco issue, not a licensed issue.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/1781

**Comment by ferventcoder** [comment]
This will be fixed as part of Chocolatey v0.10.14 based on https://github.com/chocolatey/choco/issues/1781.
