### ISSUE TITLE
Self-Service - Incorrect handling in username does not allow self-service users to uninstall based on extra character present

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#73]
### What You Are Seeing?
Background agent is incorrectly parsing username from agent configuration
### What is Expected?
Usernames match up

### Output Log

2019-03-25 11:02:46,117 4216 [DEBUG] - Username found for 'GoogleChrome' is 'test-user''. Current user is 'test-user'

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/275)

**Comment by ferventcoder** [comment]
This has been completed for Chocolatey Licensed Extension v2.0.1.
