### ISSUE TITLE
Self-Service - Administrators being subjected to self-service on uninstall when the check shouldn't apply

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#77]
### What You Are Seeing?
With the feature enabled administrators are not able to uninstall software, when they should not be subjected to that feature flag

### What is Expected?

Administrative users should be able to uninstall packages irregardless of user context during installation

### References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/282)

**Comment by ferventcoder** [comment]
This is fixed and will be released as part of Chocolatey Licensed Extension v2.0.2.
