### ISSUE TITLE
Tab completion not working on optimize

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey-licensed-issues#79]
### What You Are Seeing?
Tab completion not working for optimize, but working for other commands. 

### What is Expected?
Tab completion to work with optimize (and perhaps other licensed features)

### How Did You Get This To Happen? (Steps to Reproduce)
Install:
chocolatey v0.10.14-beta-20190418
chocolatey.extension v2.0.2

type: `choco opti` and press [TAB]

Tested on: Windows Server 2016, Windows 10

### Output Log
N/A

**Comment by ferventcoder** [comment]
Thanks for logging that - there are some others that need to be added as well.

**Comment by ferventcoder** [comment]
This will be released in Chocolatey v0.10.14 - https://github.com/chocolatey/choco/issues/1834

**Comment by ferventcoder** [comment]
Github didn't let me transfer this issue - it was emptying out the list of possible transfer options due to a forbidden error. So I just created the other issue and marked this as a duplicate. We might have removed or have not yet created the Wrong Repository issue.
