### ISSUE TITLE
Central Management - When setting SMTP configuration the SSL checkbox status is being ignored

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#87]
### What You Are Seeing?
"An Internal Error Occurred" Message when sending a test mail message

### What is Expected?
A successful test message is sent

### How Did You Get This To Happen? (Steps to Reproduce)
Fill in IP/FQDN of smtp server, From Address, Display Name, and To address. Leave SSL and other settings alone and press the Test Mail button.

### Output Log

Logs in customer ticket

### References
Internal Ticket - https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/127

**Comment by gep13** [comment]
This is completed to be released with CCM v0.1.1
