### ISSUE TITLE
Chocolatey - Error when using {} in package parameters or silentArgs

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#88]
### What You Are Seeing?

Chocolatey throws an index zero based exception when passing GUIDs in parameters

### What is Expected?

GUIDS can be passed appropriately

### How Did You Get This To Happen? (Steps to Reproduce)

`choco install bob --params="'{RandomGUID}'"`

When passing a GUID in args with curly braces, an Index Zero based  error is thrown. This error does not occur in the FOSS version of choco

## Other Information

* Chocolatey Version - 0.10.15
* Chocolatey.Extension Version - 2.0.2

## References

* [Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/288)

**Comment by ferventcoder** [comment]
Here is another similar issue that came through a while back - https://groups.google.com/forum/#!topic/chocolatey/l29DgGpoqTc

**Comment by ferventcoder** [comment]
This is fixed for v2.0.3
