### ISSUE TITLE
Package Builder - Ensure checksums are calculated correctly when using both x86 and x64 urls that result in the same file name

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey-licensed-issues#94]
### What You Are Seeing?
After executing the following command. I got a `chocolateyInstall.ps1` file with two the same checksums.
`choco new SQL2014.ClrTypes --url=https://download.microsoft.com/download/F/E/E/FEE62C90-E5A9-4746-8478-11980609E5C2/ENU/x86/SQLSysClrTypes.msi --url64=https://download.microsoft.com/download/F/E/E/FEE62C90-E5A9-4746-8478-11980609E5C2/ENU/x64/SQLSysClrTypes.msi --keep-remote`

### What is Expected?
Having different checksums (as binary files differ)

### How Did You Get This To Happen? (Steps to Reproduce)
Run the above command.

### Output Log
```
Chocolatey v0.10.15 Business
Downloading remote files, this could take a little bit of time.
Downloading: 100% - 2,22 MB
Download of 'SQLSysClrTypes.msi' completed.
Downloading: 100% - 3,09 MB
Download of 'SQLSysClrTypes.msi' completed.
Unable to update template path (likely due to permissions). May result in incorrectly generated packaging:
 Access to the path 'file.nuspec' is denied.
Creating a new package specification at D:\temp\temp2\SQL2014.ClrTypes
Generating package from custom template at 'C:\ProgramData\chocolatey\templates\NewFileInstaller'.
Generating template to a file
 at 'D:\temp\SQL2014.ClrTypes\sql2014.clrtypes.nuspec'
Generating template to a file
 at 'D:\temp\SQL2014.ClrTypes\tools\chocolateyinstall.ps1'
Successfully generated SQL2014.ClrTypes package specification files
 at 'D:\temp\SQL2014.ClrTypes'
```

### Versions
Chocolatey: 0.10.15
Chocolatey.extension: 2.0.2
Powershell: 5.1.18362.145
Windows: 10.0.18362.0

### References
* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/4433)

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/390) by [Unito](https://www.unito.io)
┆Milestone: 3.0.0

**Comment by ferventcoder** [comment]
> `Unable to update template path (likely due to permissions). May result in incorrectly generated packaging: Access to the path 'file.nuspec' is denied.`

Can we get it not to have this issue first and then see if there is an issue?

**Comment by mkevenaar** [comment]
> Can we get it not to have this issue first and then see if there is an issue?

That was just me, not running this elevated.

Same result though:
```
D:\temp\temp2> choco new SQL2014.ClrTypes3 --url=https://download.microsoft.com/download/F/E/E/FEE62C90-E5A9-4746-8478-11980609E5C2/ENU/x86/SQLSysClrTypes.msi --url64=https://download.microsoft.com/download/F/E/E/FEE62C90-E5A9-4746-8478-11980609E5C2/ENU/x64/SQLSysClrTypes.msi --keep-remote
Chocolatey v0.10.15 Business
Downloading remote files, this could take a little bit of time.
Downloading: 100% - 2,22 MB
Download of 'SQLSysClrTypes.msi' completed.
Downloading: 100% - 3,09 MB
Download of 'SQLSysClrTypes.msi' completed.
Creating a new package specification at D:\temp\temp2\SQL2014.ClrTypes3
Generating package from custom template at 'C:\ProgramData\chocolatey\templates\NewFileInstaller'.
Generating template to a file
 at 'D:\temp\temp2\SQL2014.ClrTypes3\sql2014.clrtypes3.nuspec'
Generating template to a file
 at 'D:\temp\temp2\SQL2014.ClrTypes3\tools\chocolateyinstall.ps1'
Successfully generated SQL2014.ClrTypes3 package specification files
 at 'D:\temp\temp2\SQL2014.ClrTypes3'
D:\temp\temp2> c:\tools\grep -i checksum .\SQL2014.ClrTypes3\tools\chocolateyinstall.ps1
  checksum      = 'D264B0B4D8E503C2638C18F09FF74F895DA92A9984D2B7C5D6192A6A22FA3C41'
  checksumType  = 'sha256'
  checksum64    = 'D264B0B4D8E503C2638C18F09FF74F895DA92A9984D2B7C5D6192A6A22FA3C41'
  checksumType64= 'sha256'
```

Also @pauby and @gep13 are having the same result.

@gep13 mentioned to me:
> The underlying problem is likely to do with the filename being the same for each URL

**Comment by ferventcoder** [comment]
Ah, cool. Please submit a ticket with a full log to the support email as well and reference this ticket. That way we can get it looked at.
