### ISSUE TITLE
Chocolatey Agent - "The remote server returned an unexpected response: (413) Request Entity Too Large."

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#95]
### What You Are Seeing?

When attempting to collect data on a system with >200 chocolatey packages installed the following is logged by Chocolatey Agent when attempting to submit the data to CCM:

"The remote server returned an unexpected response: (413) Request Entity Too Large."

### How Did You Get This To Happen? (Steps to Reproduce)

Configure chocolatey agent to use CCM on a system with >200 packages installed.

### References

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/130)

**Comment by ferventcoder** [comment]
This is completed for Chocolatey Licensed Extension v2.0.3 and Chocolatey Central Management v0.1.1.
