### ISSUE TITLE
Central Management -  Unable to parse netsh entries that contain hostname:port bindings

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#96]
### What You Are Seeing?

When using SNI mode, existing netsh bindings for hostname:port are ignored and a self signed certificate is generated and used.

### What is Expected?

Netsh bindings configured with a hostname are found and used

### References

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/issues/129)

**Comment by ferventcoder** [comment]
This is completed to be released with CCM v0.1.1
