### ISSUE TITLE
Central Management - Time discrepancy between Computers and Computer Details panes

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#97]
### What You Are Seeing?
It appears the time shown between two screens is off - and they should match based on the timezone.

### What is Expected?

Times should be consistent

### References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/issues/295)
[ZenDesk](https://chocolatey.zendesk.com/agent/tickets/4534)

**Comment by gep13** [comment]
This is completed to be released with CCM v0.1.1
